name: .NET

on:
  push:
    branches: ['master', 'practice']

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build (Day 9 Task 1)
        run: dotnet publish -c "Day 9 Task 1" -f net7.0 -r win-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true

      - name: Build (Day 9 Task 2)
        run: dotnet publish -c "Day 9 Task 2" -f net7.0 -r win-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true

      - name: Publish
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          title: 'Latest build (${{ github.ref_name }})'
          files: |
            './SharpLabs/bin/Day 9 Task 1/net7.0/win-x64/publish/SharpLabs.exe'
            './SharpLabs/bin/Day 9 Task 2/net7.0/win-x64/publish/SharpLabs.exe'

          prerelease: false
