name: .NET

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build ${{ matrix.target-os.name }} ${{ matrix.target.name }}'
    strategy:
      fail-fast: true
      matrix:
        target-os:
          - name: 'win-x64'
            filename: SharpLabs.exe
            ext: '.exe'

        target:
          - name: 'General'
            artifact: 'SharpLabs.General'

          - name: 'Day 9 Task 1'
            artifact: 'SharpLabs.Day9.Task1'

          - name: 'Day 9 Task 2'
            artifact: 'SharpLabs.Day9.Task2'

          - name: 'Day 10'
            artifact: 'SharpLabs.Day10'

          - name: 'Day 11'
            artifact: 'SharpLabs.Day11'

          - name: 'Day 12'
            artifact: 'SharpLabs.Day12'

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet publish -c "${{ matrix.target.name }}" -f net7.0 -r ${{ matrix.target-os.name }} -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true

      - name: Pack
        run: |
          mkdir "${{ matrix.target-os.name }}"
          mv "./SharpLabs/bin/${{ matrix.target.name }}/net7.0/${{ matrix.target-os.name }}/publish/${{ matrix.target-os.filename }}" "${{ matrix.target-os.name }}/${{ matrix.target.artifact }}${{ matrix.target-os.ext }}"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: SharpLabs
          path: '${{ matrix.target-os.name }}'

  upload:
    runs-on: ubuntu-latest
    name: 'Upload artifacts'

    steps:
      - name: Download produced artifacts
        uses: actions/download-artifact@v3
        with:
          name: SharpLabs
          path: SharpLabs

      - name: Publish release
        uses: marvinpinto/action-automatic-releases@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          title: Latest build
          files: SharpLabs
          prerelease: false
