name: .NET

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build ${{ matrix.target }}'
    strategy:
      matrix:
        include:
          - target: 'General'
            artifact: 'SharpLabs.General.exe'

          - target: 'Day 9 Task 1'
            artifact: 'SharpLabs.Day9.Task1.exe'

          - target: 'Day 9 Task 2'
            artifact: 'SharpLabs.Day9.Task2.exe'

          - target: 'Day 10'
            artifact: 'SharpLabs.Day10.exe'

          - target: 'Day 11'
            artifact: 'SharpLabs.Day11.exe'

          - target: 'Day 12'
            artifact: 'SharpLabs.Day12.exe'

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet publish -c "${{ matrix.target }}" -f net7.0 -r win-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: '**/*/SharpLabs.exe'
